services:
  # 后端服务
  backend:
    image: crpi-8mw6zrxo8n10fjq0.cn-beijing.personal.cr.aliyuncs.com/qj_szr_docker/ai_novel-backend:latest
    container_name: novel-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # 请修改为你的外部MySQL服务器地址
      SPRING_DATASOURCE_URL: jdbc:mysql://45.192.98.207:3306/ai_novel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ai_novel
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - novel-network
    restart: unless-stopped

  # 前端服务
  frontend:
    image: crpi-8mw6zrxo8n10fjq0.cn-beijing.personal.cr.aliyuncs.com/qj_szr_docker/ai_novel-frontend:latest
    container_name: novel-frontend
    ports:
      - "8701:80"
    depends_on:
      - backend
    networks:
      - novel-network
    restart: unless-stopped

networks:
  novel-network:
    driver: bridge 