spring:
  datasource:
    url: jdbc:mysql://mysql:3306/ai_novel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: novel_user
    password: novel123
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: redis
    port: 6379

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.novel: INFO
    org.springframework.security: INFO
    com.baomidou.mybatisplus: DEBUG

# Docker环境特殊配置
docker:
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: false 